// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scmmessages.proto

package com.scm.resources;

public interface ConnectReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.scm.resources.ConnectReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool confirmation = 1;</code>
   * @return The confirmation.
   */
  boolean getConfirmation();
}
