// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scmmessages.proto

package com.scm.resources;

public interface ConnectRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.scm.resources.ConnectRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string server = 1;</code>
   * @return The server.
   */
  java.lang.String getServer();
  /**
   * <code>string server = 1;</code>
   * @return The bytes for server.
   */
  com.google.protobuf.ByteString
      getServerBytes();
}
