// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scmmessages.proto

package com.scm.resources;

public interface GroupsReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.scm.resources.GroupsReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string groupNames = 1;</code>
   */
  java.util.List<java.lang.String>
      getGroupNamesList();
  /**
   * <code>repeated string groupNames = 1;</code>
   */
  int getGroupNamesCount();
  /**
   * <code>repeated string groupNames = 1;</code>
   */
  java.lang.String getGroupNames(int index);
  /**
   * <code>repeated string groupNames = 1;</code>
   */
  com.google.protobuf.ByteString
      getGroupNamesBytes(int index);
}
