// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scmmessages.proto

package com.scm.resources;

public interface GroupTagsReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.scm.resources.GroupTagsReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string tagNames = 1;</code>
   */
  java.util.List<java.lang.String>
      getTagNamesList();
  /**
   * <code>repeated string tagNames = 1;</code>
   */
  int getTagNamesCount();
  /**
   * <code>repeated string tagNames = 1;</code>
   */
  java.lang.String getTagNames(int index);
  /**
   * <code>repeated string tagNames = 1;</code>
   */
  com.google.protobuf.ByteString
      getTagNamesBytes(int index);
}
