// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scmmessages.proto

package com.scm.resources;

/**
 * Protobuf type {@code com.scm.resources.GroupsReply}
 */
public  final class GroupsReply extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.scm.resources.GroupsReply)
    GroupsReplyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GroupsReply.newBuilder() to construct.
  private GroupsReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GroupsReply() {
    groupNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GroupsReply(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              groupNames_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            groupNames_.add(s);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        groupNames_ = groupNames_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.scm.resources.Scmmessages.internal_static_com_scm_resources_GroupsReply_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.scm.resources.Scmmessages.internal_static_com_scm_resources_GroupsReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.scm.resources.GroupsReply.class, com.scm.resources.GroupsReply.Builder.class);
  }

  public static final int GROUPNAMES_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList groupNames_;
  /**
   * <code>repeated string groupNames = 1;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getGroupNamesList() {
    return groupNames_;
  }
  /**
   * <code>repeated string groupNames = 1;</code>
   */
  public int getGroupNamesCount() {
    return groupNames_.size();
  }
  /**
   * <code>repeated string groupNames = 1;</code>
   */
  public java.lang.String getGroupNames(int index) {
    return groupNames_.get(index);
  }
  /**
   * <code>repeated string groupNames = 1;</code>
   */
  public com.google.protobuf.ByteString
      getGroupNamesBytes(int index) {
    return groupNames_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < groupNames_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, groupNames_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < groupNames_.size(); i++) {
        dataSize += computeStringSizeNoTag(groupNames_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getGroupNamesList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.scm.resources.GroupsReply)) {
      return super.equals(obj);
    }
    com.scm.resources.GroupsReply other = (com.scm.resources.GroupsReply) obj;

    boolean result = true;
    result = result && getGroupNamesList()
        .equals(other.getGroupNamesList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getGroupNamesCount() > 0) {
      hash = (37 * hash) + GROUPNAMES_FIELD_NUMBER;
      hash = (53 * hash) + getGroupNamesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.scm.resources.GroupsReply parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.scm.resources.GroupsReply parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.scm.resources.GroupsReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.scm.resources.GroupsReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.scm.resources.GroupsReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.scm.resources.GroupsReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.scm.resources.GroupsReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.scm.resources.GroupsReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.scm.resources.GroupsReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.scm.resources.GroupsReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.scm.resources.GroupsReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.scm.resources.GroupsReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.scm.resources.GroupsReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.scm.resources.GroupsReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.scm.resources.GroupsReply)
      com.scm.resources.GroupsReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.scm.resources.Scmmessages.internal_static_com_scm_resources_GroupsReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.scm.resources.Scmmessages.internal_static_com_scm_resources_GroupsReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.scm.resources.GroupsReply.class, com.scm.resources.GroupsReply.Builder.class);
    }

    // Construct using com.scm.resources.GroupsReply.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      groupNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.scm.resources.Scmmessages.internal_static_com_scm_resources_GroupsReply_descriptor;
    }

    @java.lang.Override
    public com.scm.resources.GroupsReply getDefaultInstanceForType() {
      return com.scm.resources.GroupsReply.getDefaultInstance();
    }

    @java.lang.Override
    public com.scm.resources.GroupsReply build() {
      com.scm.resources.GroupsReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.scm.resources.GroupsReply buildPartial() {
      com.scm.resources.GroupsReply result = new com.scm.resources.GroupsReply(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        groupNames_ = groupNames_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.groupNames_ = groupNames_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.scm.resources.GroupsReply) {
        return mergeFrom((com.scm.resources.GroupsReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.scm.resources.GroupsReply other) {
      if (other == com.scm.resources.GroupsReply.getDefaultInstance()) return this;
      if (!other.groupNames_.isEmpty()) {
        if (groupNames_.isEmpty()) {
          groupNames_ = other.groupNames_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureGroupNamesIsMutable();
          groupNames_.addAll(other.groupNames_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.scm.resources.GroupsReply parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.scm.resources.GroupsReply) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList groupNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureGroupNamesIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        groupNames_ = new com.google.protobuf.LazyStringArrayList(groupNames_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string groupNames = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getGroupNamesList() {
      return groupNames_.getUnmodifiableView();
    }
    /**
     * <code>repeated string groupNames = 1;</code>
     */
    public int getGroupNamesCount() {
      return groupNames_.size();
    }
    /**
     * <code>repeated string groupNames = 1;</code>
     */
    public java.lang.String getGroupNames(int index) {
      return groupNames_.get(index);
    }
    /**
     * <code>repeated string groupNames = 1;</code>
     */
    public com.google.protobuf.ByteString
        getGroupNamesBytes(int index) {
      return groupNames_.getByteString(index);
    }
    /**
     * <code>repeated string groupNames = 1;</code>
     */
    public Builder setGroupNames(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureGroupNamesIsMutable();
      groupNames_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string groupNames = 1;</code>
     */
    public Builder addGroupNames(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureGroupNamesIsMutable();
      groupNames_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string groupNames = 1;</code>
     */
    public Builder addAllGroupNames(
        java.lang.Iterable<java.lang.String> values) {
      ensureGroupNamesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, groupNames_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string groupNames = 1;</code>
     */
    public Builder clearGroupNames() {
      groupNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string groupNames = 1;</code>
     */
    public Builder addGroupNamesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureGroupNamesIsMutable();
      groupNames_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.scm.resources.GroupsReply)
  }

  // @@protoc_insertion_point(class_scope:com.scm.resources.GroupsReply)
  private static final com.scm.resources.GroupsReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.scm.resources.GroupsReply();
  }

  public static com.scm.resources.GroupsReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GroupsReply>
      PARSER = new com.google.protobuf.AbstractParser<GroupsReply>() {
    @java.lang.Override
    public GroupsReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GroupsReply(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GroupsReply> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GroupsReply> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.scm.resources.GroupsReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

