// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scmmessages.proto

package com.scm.resources;

public interface GroupTagsReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.scm.resources.GroupTagsReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string tagNames = 1;</code>
   * @return A list containing the tagNames.
   */
  java.util.List<java.lang.String>
      getTagNamesList();
  /**
   * <code>repeated string tagNames = 1;</code>
   * @return The count of tagNames.
   */
  int getTagNamesCount();
  /**
   * <code>repeated string tagNames = 1;</code>
   * @param index The index of the element to return.
   * @return The tagNames at the given index.
   */
  java.lang.String getTagNames(int index);
  /**
   * <code>repeated string tagNames = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the tagNames at the given index.
   */
  com.google.protobuf.ByteString
      getTagNamesBytes(int index);
}
