// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scmmessages.proto

package com.scm.resources;

public interface GroupTagsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.scm.resources.GroupTagsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string groupName = 1;</code>
   */
  java.lang.String getGroupName();
  /**
   * <code>string groupName = 1;</code>
   */
  com.google.protobuf.ByteString
      getGroupNameBytes();
}
