// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scmmessages.proto

package com.scm.resources;

public interface MultipleTagsReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.scm.resources.MultipleTagsReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.scm.resources.TagReply tagReply = 1;</code>
   */
  java.util.List<com.scm.resources.TagReply> 
      getTagReplyList();
  /**
   * <code>repeated .com.scm.resources.TagReply tagReply = 1;</code>
   */
  com.scm.resources.TagReply getTagReply(int index);
  /**
   * <code>repeated .com.scm.resources.TagReply tagReply = 1;</code>
   */
  int getTagReplyCount();
  /**
   * <code>repeated .com.scm.resources.TagReply tagReply = 1;</code>
   */
  java.util.List<? extends com.scm.resources.TagReplyOrBuilder> 
      getTagReplyOrBuilderList();
  /**
   * <code>repeated .com.scm.resources.TagReply tagReply = 1;</code>
   */
  com.scm.resources.TagReplyOrBuilder getTagReplyOrBuilder(
      int index);
}
