// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scmmessages.proto

package com.scm.resources;

public interface MultipleTagsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.scm.resources.MultipleTagsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.scm.resources.TagRequest tagRequest = 1;</code>
   */
  java.util.List<com.scm.resources.TagRequest> 
      getTagRequestList();
  /**
   * <code>repeated .com.scm.resources.TagRequest tagRequest = 1;</code>
   */
  com.scm.resources.TagRequest getTagRequest(int index);
  /**
   * <code>repeated .com.scm.resources.TagRequest tagRequest = 1;</code>
   */
  int getTagRequestCount();
  /**
   * <code>repeated .com.scm.resources.TagRequest tagRequest = 1;</code>
   */
  java.util.List<? extends com.scm.resources.TagRequestOrBuilder> 
      getTagRequestOrBuilderList();
  /**
   * <code>repeated .com.scm.resources.TagRequest tagRequest = 1;</code>
   */
  com.scm.resources.TagRequestOrBuilder getTagRequestOrBuilder(
      int index);
}
