// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scmmessages.proto

package com.scm.resources;

/**
 * Protobuf type {@code com.scm.resources.MultipleTagsReply}
 */
public  final class MultipleTagsReply extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.scm.resources.MultipleTagsReply)
    MultipleTagsReplyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MultipleTagsReply.newBuilder() to construct.
  private MultipleTagsReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MultipleTagsReply() {
    tagReply_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MultipleTagsReply(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              tagReply_ = new java.util.ArrayList<com.scm.resources.TagReply>();
              mutable_bitField0_ |= 0x00000001;
            }
            tagReply_.add(
                input.readMessage(com.scm.resources.TagReply.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        tagReply_ = java.util.Collections.unmodifiableList(tagReply_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.scm.resources.Scmmessages.internal_static_com_scm_resources_MultipleTagsReply_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.scm.resources.Scmmessages.internal_static_com_scm_resources_MultipleTagsReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.scm.resources.MultipleTagsReply.class, com.scm.resources.MultipleTagsReply.Builder.class);
  }

  public static final int TAGREPLY_FIELD_NUMBER = 1;
  private java.util.List<com.scm.resources.TagReply> tagReply_;
  /**
   * <code>repeated .com.scm.resources.TagReply tagReply = 1;</code>
   */
  public java.util.List<com.scm.resources.TagReply> getTagReplyList() {
    return tagReply_;
  }
  /**
   * <code>repeated .com.scm.resources.TagReply tagReply = 1;</code>
   */
  public java.util.List<? extends com.scm.resources.TagReplyOrBuilder> 
      getTagReplyOrBuilderList() {
    return tagReply_;
  }
  /**
   * <code>repeated .com.scm.resources.TagReply tagReply = 1;</code>
   */
  public int getTagReplyCount() {
    return tagReply_.size();
  }
  /**
   * <code>repeated .com.scm.resources.TagReply tagReply = 1;</code>
   */
  public com.scm.resources.TagReply getTagReply(int index) {
    return tagReply_.get(index);
  }
  /**
   * <code>repeated .com.scm.resources.TagReply tagReply = 1;</code>
   */
  public com.scm.resources.TagReplyOrBuilder getTagReplyOrBuilder(
      int index) {
    return tagReply_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < tagReply_.size(); i++) {
      output.writeMessage(1, tagReply_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < tagReply_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, tagReply_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.scm.resources.MultipleTagsReply)) {
      return super.equals(obj);
    }
    com.scm.resources.MultipleTagsReply other = (com.scm.resources.MultipleTagsReply) obj;

    boolean result = true;
    result = result && getTagReplyList()
        .equals(other.getTagReplyList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getTagReplyCount() > 0) {
      hash = (37 * hash) + TAGREPLY_FIELD_NUMBER;
      hash = (53 * hash) + getTagReplyList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.scm.resources.MultipleTagsReply parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.scm.resources.MultipleTagsReply parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.scm.resources.MultipleTagsReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.scm.resources.MultipleTagsReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.scm.resources.MultipleTagsReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.scm.resources.MultipleTagsReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.scm.resources.MultipleTagsReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.scm.resources.MultipleTagsReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.scm.resources.MultipleTagsReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.scm.resources.MultipleTagsReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.scm.resources.MultipleTagsReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.scm.resources.MultipleTagsReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.scm.resources.MultipleTagsReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.scm.resources.MultipleTagsReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.scm.resources.MultipleTagsReply)
      com.scm.resources.MultipleTagsReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.scm.resources.Scmmessages.internal_static_com_scm_resources_MultipleTagsReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.scm.resources.Scmmessages.internal_static_com_scm_resources_MultipleTagsReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.scm.resources.MultipleTagsReply.class, com.scm.resources.MultipleTagsReply.Builder.class);
    }

    // Construct using com.scm.resources.MultipleTagsReply.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getTagReplyFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (tagReplyBuilder_ == null) {
        tagReply_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        tagReplyBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.scm.resources.Scmmessages.internal_static_com_scm_resources_MultipleTagsReply_descriptor;
    }

    @java.lang.Override
    public com.scm.resources.MultipleTagsReply getDefaultInstanceForType() {
      return com.scm.resources.MultipleTagsReply.getDefaultInstance();
    }

    @java.lang.Override
    public com.scm.resources.MultipleTagsReply build() {
      com.scm.resources.MultipleTagsReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.scm.resources.MultipleTagsReply buildPartial() {
      com.scm.resources.MultipleTagsReply result = new com.scm.resources.MultipleTagsReply(this);
      int from_bitField0_ = bitField0_;
      if (tagReplyBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          tagReply_ = java.util.Collections.unmodifiableList(tagReply_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.tagReply_ = tagReply_;
      } else {
        result.tagReply_ = tagReplyBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.scm.resources.MultipleTagsReply) {
        return mergeFrom((com.scm.resources.MultipleTagsReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.scm.resources.MultipleTagsReply other) {
      if (other == com.scm.resources.MultipleTagsReply.getDefaultInstance()) return this;
      if (tagReplyBuilder_ == null) {
        if (!other.tagReply_.isEmpty()) {
          if (tagReply_.isEmpty()) {
            tagReply_ = other.tagReply_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureTagReplyIsMutable();
            tagReply_.addAll(other.tagReply_);
          }
          onChanged();
        }
      } else {
        if (!other.tagReply_.isEmpty()) {
          if (tagReplyBuilder_.isEmpty()) {
            tagReplyBuilder_.dispose();
            tagReplyBuilder_ = null;
            tagReply_ = other.tagReply_;
            bitField0_ = (bitField0_ & ~0x00000001);
            tagReplyBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getTagReplyFieldBuilder() : null;
          } else {
            tagReplyBuilder_.addAllMessages(other.tagReply_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.scm.resources.MultipleTagsReply parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.scm.resources.MultipleTagsReply) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.scm.resources.TagReply> tagReply_ =
      java.util.Collections.emptyList();
    private void ensureTagReplyIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        tagReply_ = new java.util.ArrayList<com.scm.resources.TagReply>(tagReply_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.scm.resources.TagReply, com.scm.resources.TagReply.Builder, com.scm.resources.TagReplyOrBuilder> tagReplyBuilder_;

    /**
     * <code>repeated .com.scm.resources.TagReply tagReply = 1;</code>
     */
    public java.util.List<com.scm.resources.TagReply> getTagReplyList() {
      if (tagReplyBuilder_ == null) {
        return java.util.Collections.unmodifiableList(tagReply_);
      } else {
        return tagReplyBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.scm.resources.TagReply tagReply = 1;</code>
     */
    public int getTagReplyCount() {
      if (tagReplyBuilder_ == null) {
        return tagReply_.size();
      } else {
        return tagReplyBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.scm.resources.TagReply tagReply = 1;</code>
     */
    public com.scm.resources.TagReply getTagReply(int index) {
      if (tagReplyBuilder_ == null) {
        return tagReply_.get(index);
      } else {
        return tagReplyBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.scm.resources.TagReply tagReply = 1;</code>
     */
    public Builder setTagReply(
        int index, com.scm.resources.TagReply value) {
      if (tagReplyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTagReplyIsMutable();
        tagReply_.set(index, value);
        onChanged();
      } else {
        tagReplyBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.scm.resources.TagReply tagReply = 1;</code>
     */
    public Builder setTagReply(
        int index, com.scm.resources.TagReply.Builder builderForValue) {
      if (tagReplyBuilder_ == null) {
        ensureTagReplyIsMutable();
        tagReply_.set(index, builderForValue.build());
        onChanged();
      } else {
        tagReplyBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.scm.resources.TagReply tagReply = 1;</code>
     */
    public Builder addTagReply(com.scm.resources.TagReply value) {
      if (tagReplyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTagReplyIsMutable();
        tagReply_.add(value);
        onChanged();
      } else {
        tagReplyBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.scm.resources.TagReply tagReply = 1;</code>
     */
    public Builder addTagReply(
        int index, com.scm.resources.TagReply value) {
      if (tagReplyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTagReplyIsMutable();
        tagReply_.add(index, value);
        onChanged();
      } else {
        tagReplyBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.scm.resources.TagReply tagReply = 1;</code>
     */
    public Builder addTagReply(
        com.scm.resources.TagReply.Builder builderForValue) {
      if (tagReplyBuilder_ == null) {
        ensureTagReplyIsMutable();
        tagReply_.add(builderForValue.build());
        onChanged();
      } else {
        tagReplyBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.scm.resources.TagReply tagReply = 1;</code>
     */
    public Builder addTagReply(
        int index, com.scm.resources.TagReply.Builder builderForValue) {
      if (tagReplyBuilder_ == null) {
        ensureTagReplyIsMutable();
        tagReply_.add(index, builderForValue.build());
        onChanged();
      } else {
        tagReplyBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.scm.resources.TagReply tagReply = 1;</code>
     */
    public Builder addAllTagReply(
        java.lang.Iterable<? extends com.scm.resources.TagReply> values) {
      if (tagReplyBuilder_ == null) {
        ensureTagReplyIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, tagReply_);
        onChanged();
      } else {
        tagReplyBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.scm.resources.TagReply tagReply = 1;</code>
     */
    public Builder clearTagReply() {
      if (tagReplyBuilder_ == null) {
        tagReply_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        tagReplyBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.scm.resources.TagReply tagReply = 1;</code>
     */
    public Builder removeTagReply(int index) {
      if (tagReplyBuilder_ == null) {
        ensureTagReplyIsMutable();
        tagReply_.remove(index);
        onChanged();
      } else {
        tagReplyBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.scm.resources.TagReply tagReply = 1;</code>
     */
    public com.scm.resources.TagReply.Builder getTagReplyBuilder(
        int index) {
      return getTagReplyFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.scm.resources.TagReply tagReply = 1;</code>
     */
    public com.scm.resources.TagReplyOrBuilder getTagReplyOrBuilder(
        int index) {
      if (tagReplyBuilder_ == null) {
        return tagReply_.get(index);  } else {
        return tagReplyBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.scm.resources.TagReply tagReply = 1;</code>
     */
    public java.util.List<? extends com.scm.resources.TagReplyOrBuilder> 
         getTagReplyOrBuilderList() {
      if (tagReplyBuilder_ != null) {
        return tagReplyBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(tagReply_);
      }
    }
    /**
     * <code>repeated .com.scm.resources.TagReply tagReply = 1;</code>
     */
    public com.scm.resources.TagReply.Builder addTagReplyBuilder() {
      return getTagReplyFieldBuilder().addBuilder(
          com.scm.resources.TagReply.getDefaultInstance());
    }
    /**
     * <code>repeated .com.scm.resources.TagReply tagReply = 1;</code>
     */
    public com.scm.resources.TagReply.Builder addTagReplyBuilder(
        int index) {
      return getTagReplyFieldBuilder().addBuilder(
          index, com.scm.resources.TagReply.getDefaultInstance());
    }
    /**
     * <code>repeated .com.scm.resources.TagReply tagReply = 1;</code>
     */
    public java.util.List<com.scm.resources.TagReply.Builder> 
         getTagReplyBuilderList() {
      return getTagReplyFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.scm.resources.TagReply, com.scm.resources.TagReply.Builder, com.scm.resources.TagReplyOrBuilder> 
        getTagReplyFieldBuilder() {
      if (tagReplyBuilder_ == null) {
        tagReplyBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.scm.resources.TagReply, com.scm.resources.TagReply.Builder, com.scm.resources.TagReplyOrBuilder>(
                tagReply_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        tagReply_ = null;
      }
      return tagReplyBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.scm.resources.MultipleTagsReply)
  }

  // @@protoc_insertion_point(class_scope:com.scm.resources.MultipleTagsReply)
  private static final com.scm.resources.MultipleTagsReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.scm.resources.MultipleTagsReply();
  }

  public static com.scm.resources.MultipleTagsReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MultipleTagsReply>
      PARSER = new com.google.protobuf.AbstractParser<MultipleTagsReply>() {
    @java.lang.Override
    public MultipleTagsReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MultipleTagsReply(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MultipleTagsReply> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MultipleTagsReply> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.scm.resources.MultipleTagsReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

