// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scmmessages.proto

package com.scm.resources;

/**
 * Protobuf type {@code com.scm.resources.MultipleTagsRequest}
 */
public  final class MultipleTagsRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.scm.resources.MultipleTagsRequest)
    MultipleTagsRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MultipleTagsRequest.newBuilder() to construct.
  private MultipleTagsRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MultipleTagsRequest() {
    tagRequest_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MultipleTagsRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MultipleTagsRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              tagRequest_ = new java.util.ArrayList<com.scm.resources.TagRequest>();
              mutable_bitField0_ |= 0x00000001;
            }
            tagRequest_.add(
                input.readMessage(com.scm.resources.TagRequest.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        tagRequest_ = java.util.Collections.unmodifiableList(tagRequest_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.scm.resources.Scmmessages.internal_static_com_scm_resources_MultipleTagsRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.scm.resources.Scmmessages.internal_static_com_scm_resources_MultipleTagsRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.scm.resources.MultipleTagsRequest.class, com.scm.resources.MultipleTagsRequest.Builder.class);
  }

  public static final int TAGREQUEST_FIELD_NUMBER = 1;
  private java.util.List<com.scm.resources.TagRequest> tagRequest_;
  /**
   * <code>repeated .com.scm.resources.TagRequest tagRequest = 1;</code>
   */
  public java.util.List<com.scm.resources.TagRequest> getTagRequestList() {
    return tagRequest_;
  }
  /**
   * <code>repeated .com.scm.resources.TagRequest tagRequest = 1;</code>
   */
  public java.util.List<? extends com.scm.resources.TagRequestOrBuilder> 
      getTagRequestOrBuilderList() {
    return tagRequest_;
  }
  /**
   * <code>repeated .com.scm.resources.TagRequest tagRequest = 1;</code>
   */
  public int getTagRequestCount() {
    return tagRequest_.size();
  }
  /**
   * <code>repeated .com.scm.resources.TagRequest tagRequest = 1;</code>
   */
  public com.scm.resources.TagRequest getTagRequest(int index) {
    return tagRequest_.get(index);
  }
  /**
   * <code>repeated .com.scm.resources.TagRequest tagRequest = 1;</code>
   */
  public com.scm.resources.TagRequestOrBuilder getTagRequestOrBuilder(
      int index) {
    return tagRequest_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < tagRequest_.size(); i++) {
      output.writeMessage(1, tagRequest_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < tagRequest_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, tagRequest_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.scm.resources.MultipleTagsRequest)) {
      return super.equals(obj);
    }
    com.scm.resources.MultipleTagsRequest other = (com.scm.resources.MultipleTagsRequest) obj;

    if (!getTagRequestList()
        .equals(other.getTagRequestList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getTagRequestCount() > 0) {
      hash = (37 * hash) + TAGREQUEST_FIELD_NUMBER;
      hash = (53 * hash) + getTagRequestList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.scm.resources.MultipleTagsRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.scm.resources.MultipleTagsRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.scm.resources.MultipleTagsRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.scm.resources.MultipleTagsRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.scm.resources.MultipleTagsRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.scm.resources.MultipleTagsRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.scm.resources.MultipleTagsRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.scm.resources.MultipleTagsRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.scm.resources.MultipleTagsRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.scm.resources.MultipleTagsRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.scm.resources.MultipleTagsRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.scm.resources.MultipleTagsRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.scm.resources.MultipleTagsRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.scm.resources.MultipleTagsRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.scm.resources.MultipleTagsRequest)
      com.scm.resources.MultipleTagsRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.scm.resources.Scmmessages.internal_static_com_scm_resources_MultipleTagsRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.scm.resources.Scmmessages.internal_static_com_scm_resources_MultipleTagsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.scm.resources.MultipleTagsRequest.class, com.scm.resources.MultipleTagsRequest.Builder.class);
    }

    // Construct using com.scm.resources.MultipleTagsRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getTagRequestFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (tagRequestBuilder_ == null) {
        tagRequest_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        tagRequestBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.scm.resources.Scmmessages.internal_static_com_scm_resources_MultipleTagsRequest_descriptor;
    }

    @java.lang.Override
    public com.scm.resources.MultipleTagsRequest getDefaultInstanceForType() {
      return com.scm.resources.MultipleTagsRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.scm.resources.MultipleTagsRequest build() {
      com.scm.resources.MultipleTagsRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.scm.resources.MultipleTagsRequest buildPartial() {
      com.scm.resources.MultipleTagsRequest result = new com.scm.resources.MultipleTagsRequest(this);
      int from_bitField0_ = bitField0_;
      if (tagRequestBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          tagRequest_ = java.util.Collections.unmodifiableList(tagRequest_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.tagRequest_ = tagRequest_;
      } else {
        result.tagRequest_ = tagRequestBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.scm.resources.MultipleTagsRequest) {
        return mergeFrom((com.scm.resources.MultipleTagsRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.scm.resources.MultipleTagsRequest other) {
      if (other == com.scm.resources.MultipleTagsRequest.getDefaultInstance()) return this;
      if (tagRequestBuilder_ == null) {
        if (!other.tagRequest_.isEmpty()) {
          if (tagRequest_.isEmpty()) {
            tagRequest_ = other.tagRequest_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureTagRequestIsMutable();
            tagRequest_.addAll(other.tagRequest_);
          }
          onChanged();
        }
      } else {
        if (!other.tagRequest_.isEmpty()) {
          if (tagRequestBuilder_.isEmpty()) {
            tagRequestBuilder_.dispose();
            tagRequestBuilder_ = null;
            tagRequest_ = other.tagRequest_;
            bitField0_ = (bitField0_ & ~0x00000001);
            tagRequestBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getTagRequestFieldBuilder() : null;
          } else {
            tagRequestBuilder_.addAllMessages(other.tagRequest_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.scm.resources.MultipleTagsRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.scm.resources.MultipleTagsRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.scm.resources.TagRequest> tagRequest_ =
      java.util.Collections.emptyList();
    private void ensureTagRequestIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        tagRequest_ = new java.util.ArrayList<com.scm.resources.TagRequest>(tagRequest_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.scm.resources.TagRequest, com.scm.resources.TagRequest.Builder, com.scm.resources.TagRequestOrBuilder> tagRequestBuilder_;

    /**
     * <code>repeated .com.scm.resources.TagRequest tagRequest = 1;</code>
     */
    public java.util.List<com.scm.resources.TagRequest> getTagRequestList() {
      if (tagRequestBuilder_ == null) {
        return java.util.Collections.unmodifiableList(tagRequest_);
      } else {
        return tagRequestBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.scm.resources.TagRequest tagRequest = 1;</code>
     */
    public int getTagRequestCount() {
      if (tagRequestBuilder_ == null) {
        return tagRequest_.size();
      } else {
        return tagRequestBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.scm.resources.TagRequest tagRequest = 1;</code>
     */
    public com.scm.resources.TagRequest getTagRequest(int index) {
      if (tagRequestBuilder_ == null) {
        return tagRequest_.get(index);
      } else {
        return tagRequestBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.scm.resources.TagRequest tagRequest = 1;</code>
     */
    public Builder setTagRequest(
        int index, com.scm.resources.TagRequest value) {
      if (tagRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTagRequestIsMutable();
        tagRequest_.set(index, value);
        onChanged();
      } else {
        tagRequestBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.scm.resources.TagRequest tagRequest = 1;</code>
     */
    public Builder setTagRequest(
        int index, com.scm.resources.TagRequest.Builder builderForValue) {
      if (tagRequestBuilder_ == null) {
        ensureTagRequestIsMutable();
        tagRequest_.set(index, builderForValue.build());
        onChanged();
      } else {
        tagRequestBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.scm.resources.TagRequest tagRequest = 1;</code>
     */
    public Builder addTagRequest(com.scm.resources.TagRequest value) {
      if (tagRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTagRequestIsMutable();
        tagRequest_.add(value);
        onChanged();
      } else {
        tagRequestBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.scm.resources.TagRequest tagRequest = 1;</code>
     */
    public Builder addTagRequest(
        int index, com.scm.resources.TagRequest value) {
      if (tagRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTagRequestIsMutable();
        tagRequest_.add(index, value);
        onChanged();
      } else {
        tagRequestBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.scm.resources.TagRequest tagRequest = 1;</code>
     */
    public Builder addTagRequest(
        com.scm.resources.TagRequest.Builder builderForValue) {
      if (tagRequestBuilder_ == null) {
        ensureTagRequestIsMutable();
        tagRequest_.add(builderForValue.build());
        onChanged();
      } else {
        tagRequestBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.scm.resources.TagRequest tagRequest = 1;</code>
     */
    public Builder addTagRequest(
        int index, com.scm.resources.TagRequest.Builder builderForValue) {
      if (tagRequestBuilder_ == null) {
        ensureTagRequestIsMutable();
        tagRequest_.add(index, builderForValue.build());
        onChanged();
      } else {
        tagRequestBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.scm.resources.TagRequest tagRequest = 1;</code>
     */
    public Builder addAllTagRequest(
        java.lang.Iterable<? extends com.scm.resources.TagRequest> values) {
      if (tagRequestBuilder_ == null) {
        ensureTagRequestIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, tagRequest_);
        onChanged();
      } else {
        tagRequestBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.scm.resources.TagRequest tagRequest = 1;</code>
     */
    public Builder clearTagRequest() {
      if (tagRequestBuilder_ == null) {
        tagRequest_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        tagRequestBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.scm.resources.TagRequest tagRequest = 1;</code>
     */
    public Builder removeTagRequest(int index) {
      if (tagRequestBuilder_ == null) {
        ensureTagRequestIsMutable();
        tagRequest_.remove(index);
        onChanged();
      } else {
        tagRequestBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.scm.resources.TagRequest tagRequest = 1;</code>
     */
    public com.scm.resources.TagRequest.Builder getTagRequestBuilder(
        int index) {
      return getTagRequestFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.scm.resources.TagRequest tagRequest = 1;</code>
     */
    public com.scm.resources.TagRequestOrBuilder getTagRequestOrBuilder(
        int index) {
      if (tagRequestBuilder_ == null) {
        return tagRequest_.get(index);  } else {
        return tagRequestBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.scm.resources.TagRequest tagRequest = 1;</code>
     */
    public java.util.List<? extends com.scm.resources.TagRequestOrBuilder> 
         getTagRequestOrBuilderList() {
      if (tagRequestBuilder_ != null) {
        return tagRequestBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(tagRequest_);
      }
    }
    /**
     * <code>repeated .com.scm.resources.TagRequest tagRequest = 1;</code>
     */
    public com.scm.resources.TagRequest.Builder addTagRequestBuilder() {
      return getTagRequestFieldBuilder().addBuilder(
          com.scm.resources.TagRequest.getDefaultInstance());
    }
    /**
     * <code>repeated .com.scm.resources.TagRequest tagRequest = 1;</code>
     */
    public com.scm.resources.TagRequest.Builder addTagRequestBuilder(
        int index) {
      return getTagRequestFieldBuilder().addBuilder(
          index, com.scm.resources.TagRequest.getDefaultInstance());
    }
    /**
     * <code>repeated .com.scm.resources.TagRequest tagRequest = 1;</code>
     */
    public java.util.List<com.scm.resources.TagRequest.Builder> 
         getTagRequestBuilderList() {
      return getTagRequestFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.scm.resources.TagRequest, com.scm.resources.TagRequest.Builder, com.scm.resources.TagRequestOrBuilder> 
        getTagRequestFieldBuilder() {
      if (tagRequestBuilder_ == null) {
        tagRequestBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.scm.resources.TagRequest, com.scm.resources.TagRequest.Builder, com.scm.resources.TagRequestOrBuilder>(
                tagRequest_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        tagRequest_ = null;
      }
      return tagRequestBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.scm.resources.MultipleTagsRequest)
  }

  // @@protoc_insertion_point(class_scope:com.scm.resources.MultipleTagsRequest)
  private static final com.scm.resources.MultipleTagsRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.scm.resources.MultipleTagsRequest();
  }

  public static com.scm.resources.MultipleTagsRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MultipleTagsRequest>
      PARSER = new com.google.protobuf.AbstractParser<MultipleTagsRequest>() {
    @java.lang.Override
    public MultipleTagsRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MultipleTagsRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MultipleTagsRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MultipleTagsRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.scm.resources.MultipleTagsRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

