// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scmmessages.proto

package com.scm.resources;

public final class Scmmessages {
  private Scmmessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_scm_resources_ConnectRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_scm_resources_ConnectRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_scm_resources_ConnectReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_scm_resources_ConnectReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_scm_resources_GroupsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_scm_resources_GroupsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_scm_resources_GroupsReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_scm_resources_GroupsReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_scm_resources_GroupTagsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_scm_resources_GroupTagsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_scm_resources_GroupTagsReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_scm_resources_GroupTagsReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_scm_resources_TagRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_scm_resources_TagRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_scm_resources_TagReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_scm_resources_TagReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_scm_resources_MultipleTagsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_scm_resources_MultipleTagsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_scm_resources_MultipleTagsReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_scm_resources_MultipleTagsReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021scmmessages.proto\022\021com.scm.resources\" " +
      "\n\016ConnectRequest\022\016\n\006server\030\001 \001(\t\"$\n\014Conn" +
      "ectReply\022\024\n\014confirmation\030\001 \001(\010\" \n\rGroups" +
      "Request\022\017\n\007request\030\001 \001(\t\"!\n\013GroupsReply\022" +
      "\022\n\ngroupNames\030\001 \003(\t\"%\n\020GroupTagsRequest\022" +
      "\021\n\tgroupName\030\001 \001(\t\"\"\n\016GroupTagsReply\022\020\n\010" +
      "tagNames\030\001 \003(\t\"0\n\nTagRequest\022\017\n\007tagName\030" +
      "\001 \001(\t\022\021\n\tgroupName\030\002 \001(\t\"\233\001\n\010TagReply\022\024\n" +
      "\014clientHandle\030\001 \001(\t\022\020\n\010itemName\030\002 \001(\t\022\016\n" +
      "\006active\030\003 \001(\010\022\022\n\naccessPath\030\004 \001(\t\022\021\n\ttim" +
      "eStamp\030\005 \001(\003\022\020\n\010dataType\030\006 \001(\t\022\r\n\005value\030" +
      "\007 \001(\t\022\017\n\007quality\030\010 \001(\010\"H\n\023MultipleTagsRe" +
      "quest\0221\n\ntagRequest\030\001 \003(\0132\035.com.scm.reso" +
      "urces.TagRequest\"B\n\021MultipleTagsReply\022-\n" +
      "\010tagReply\030\001 \003(\0132\033.com.scm.resources.TagR" +
      "eply2\267\003\n\016MessageHandler\022O\n\007connect\022!.com" +
      ".scm.resources.ConnectRequest\032\037.com.scm." +
      "resources.ConnectReply\"\000\022O\n\tgetGroups\022 ." +
      "com.scm.resources.GroupsRequest\032\036.com.sc" +
      "m.resources.GroupsReply\"\000\022X\n\014getGroupTag" +
      "s\022#.com.scm.resources.GroupTagsRequest\032!" +
      ".com.scm.resources.GroupTagsReply\"\000\022F\n\006g" +
      "etTag\022\035.com.scm.resources.TagRequest\032\033.c" +
      "om.scm.resources.TagReply\"\000\022a\n\017getMultip" +
      "leTags\022&.com.scm.resources.MultipleTagsR" +
      "equest\032$.com.scm.resources.MultipleTagsR" +
      "eply\"\000B\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_scm_resources_ConnectRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_scm_resources_ConnectRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_scm_resources_ConnectRequest_descriptor,
        new java.lang.String[] { "Server", });
    internal_static_com_scm_resources_ConnectReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_scm_resources_ConnectReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_scm_resources_ConnectReply_descriptor,
        new java.lang.String[] { "Confirmation", });
    internal_static_com_scm_resources_GroupsRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_scm_resources_GroupsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_scm_resources_GroupsRequest_descriptor,
        new java.lang.String[] { "Request", });
    internal_static_com_scm_resources_GroupsReply_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_scm_resources_GroupsReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_scm_resources_GroupsReply_descriptor,
        new java.lang.String[] { "GroupNames", });
    internal_static_com_scm_resources_GroupTagsRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_scm_resources_GroupTagsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_scm_resources_GroupTagsRequest_descriptor,
        new java.lang.String[] { "GroupName", });
    internal_static_com_scm_resources_GroupTagsReply_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_scm_resources_GroupTagsReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_scm_resources_GroupTagsReply_descriptor,
        new java.lang.String[] { "TagNames", });
    internal_static_com_scm_resources_TagRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_scm_resources_TagRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_scm_resources_TagRequest_descriptor,
        new java.lang.String[] { "TagName", "GroupName", });
    internal_static_com_scm_resources_TagReply_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_com_scm_resources_TagReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_scm_resources_TagReply_descriptor,
        new java.lang.String[] { "ClientHandle", "ItemName", "Active", "AccessPath", "TimeStamp", "DataType", "Value", "Quality", });
    internal_static_com_scm_resources_MultipleTagsRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_com_scm_resources_MultipleTagsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_scm_resources_MultipleTagsRequest_descriptor,
        new java.lang.String[] { "TagRequest", });
    internal_static_com_scm_resources_MultipleTagsReply_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_com_scm_resources_MultipleTagsReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_scm_resources_MultipleTagsReply_descriptor,
        new java.lang.String[] { "TagReply", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
