// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scmmessages.proto

package com.scm.resources;

public interface TagGroupTwoFileRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.scm.resources.TagGroupTwoFileRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string filePathTag = 1;</code>
   * @return The filePathTag.
   */
  java.lang.String getFilePathTag();
  /**
   * <code>string filePathTag = 1;</code>
   * @return The bytes for filePathTag.
   */
  com.google.protobuf.ByteString
      getFilePathTagBytes();

  /**
   * <code>string filePathGroup = 2;</code>
   * @return The filePathGroup.
   */
  java.lang.String getFilePathGroup();
  /**
   * <code>string filePathGroup = 2;</code>
   * @return The bytes for filePathGroup.
   */
  com.google.protobuf.ByteString
      getFilePathGroupBytes();
}
