// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scmmessages.proto

package com.scm.resources;

public interface TagGroupFileRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.scm.resources.TagGroupFileRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string srcPathTagGroup = 1;</code>
   * @return The srcPathTagGroup.
   */
  java.lang.String getSrcPathTagGroup();
  /**
   * <code>string srcPathTagGroup = 1;</code>
   * @return The bytes for srcPathTagGroup.
   */
  com.google.protobuf.ByteString
      getSrcPathTagGroupBytes();

  /**
   * <code>string destPath = 2;</code>
   * @return The destPath.
   */
  java.lang.String getDestPath();
  /**
   * <code>string destPath = 2;</code>
   * @return The bytes for destPath.
   */
  com.google.protobuf.ByteString
      getDestPathBytes();
}
