// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scmmessages.proto

package com.scm.resources;

public interface TagReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.scm.resources.TagReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string clientHandle = 1;</code>
   */
  java.lang.String getClientHandle();
  /**
   * <code>string clientHandle = 1;</code>
   */
  com.google.protobuf.ByteString
      getClientHandleBytes();

  /**
   * <code>string itemName = 2;</code>
   */
  java.lang.String getItemName();
  /**
   * <code>string itemName = 2;</code>
   */
  com.google.protobuf.ByteString
      getItemNameBytes();

  /**
   * <code>bool active = 3;</code>
   */
  boolean getActive();

  /**
   * <code>string accessPath = 4;</code>
   */
  java.lang.String getAccessPath();
  /**
   * <code>string accessPath = 4;</code>
   */
  com.google.protobuf.ByteString
      getAccessPathBytes();

  /**
   * <code>int64 timeStamp = 5;</code>
   */
  long getTimeStamp();

  /**
   * <code>string dataType = 6;</code>
   */
  java.lang.String getDataType();
  /**
   * <code>string dataType = 6;</code>
   */
  com.google.protobuf.ByteString
      getDataTypeBytes();

  /**
   * <code>string value = 7;</code>
   */
  java.lang.String getValue();
  /**
   * <code>string value = 7;</code>
   */
  com.google.protobuf.ByteString
      getValueBytes();

  /**
   * <code>bool quality = 8;</code>
   */
  boolean getQuality();
}
