// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scmmessages.proto

package com.scm.resources;

public interface TagRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.scm.resources.TagRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string tagName = 1;</code>
   */
  java.lang.String getTagName();
  /**
   * <code>string tagName = 1;</code>
   */
  com.google.protobuf.ByteString
      getTagNameBytes();

  /**
   * <code>string groupName = 2;</code>
   */
  java.lang.String getGroupName();
  /**
   * <code>string groupName = 2;</code>
   */
  com.google.protobuf.ByteString
      getGroupNameBytes();
}
