// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scmmessages.proto

package com.scm.resources;

/**
 * Protobuf type {@code com.scm.resources.TagReply}
 */
public  final class TagReply extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.scm.resources.TagReply)
    TagReplyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TagReply.newBuilder() to construct.
  private TagReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TagReply() {
    clientHandle_ = "";
    itemName_ = "";
    accessPath_ = "";
    dataType_ = "";
    value_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TagReply(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            clientHandle_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            itemName_ = s;
            break;
          }
          case 24: {

            active_ = input.readBool();
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            accessPath_ = s;
            break;
          }
          case 40: {

            timeStamp_ = input.readInt64();
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            dataType_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            value_ = s;
            break;
          }
          case 64: {

            quality_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.scm.resources.Scmmessages.internal_static_com_scm_resources_TagReply_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.scm.resources.Scmmessages.internal_static_com_scm_resources_TagReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.scm.resources.TagReply.class, com.scm.resources.TagReply.Builder.class);
  }

  public static final int CLIENTHANDLE_FIELD_NUMBER = 1;
  private volatile java.lang.Object clientHandle_;
  /**
   * <code>string clientHandle = 1;</code>
   */
  public java.lang.String getClientHandle() {
    java.lang.Object ref = clientHandle_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      clientHandle_ = s;
      return s;
    }
  }
  /**
   * <code>string clientHandle = 1;</code>
   */
  public com.google.protobuf.ByteString
      getClientHandleBytes() {
    java.lang.Object ref = clientHandle_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      clientHandle_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ITEMNAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object itemName_;
  /**
   * <code>string itemName = 2;</code>
   */
  public java.lang.String getItemName() {
    java.lang.Object ref = itemName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      itemName_ = s;
      return s;
    }
  }
  /**
   * <code>string itemName = 2;</code>
   */
  public com.google.protobuf.ByteString
      getItemNameBytes() {
    java.lang.Object ref = itemName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      itemName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ACTIVE_FIELD_NUMBER = 3;
  private boolean active_;
  /**
   * <code>bool active = 3;</code>
   */
  public boolean getActive() {
    return active_;
  }

  public static final int ACCESSPATH_FIELD_NUMBER = 4;
  private volatile java.lang.Object accessPath_;
  /**
   * <code>string accessPath = 4;</code>
   */
  public java.lang.String getAccessPath() {
    java.lang.Object ref = accessPath_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      accessPath_ = s;
      return s;
    }
  }
  /**
   * <code>string accessPath = 4;</code>
   */
  public com.google.protobuf.ByteString
      getAccessPathBytes() {
    java.lang.Object ref = accessPath_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      accessPath_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 5;
  private long timeStamp_;
  /**
   * <code>int64 timeStamp = 5;</code>
   */
  public long getTimeStamp() {
    return timeStamp_;
  }

  public static final int DATATYPE_FIELD_NUMBER = 6;
  private volatile java.lang.Object dataType_;
  /**
   * <code>string dataType = 6;</code>
   */
  public java.lang.String getDataType() {
    java.lang.Object ref = dataType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dataType_ = s;
      return s;
    }
  }
  /**
   * <code>string dataType = 6;</code>
   */
  public com.google.protobuf.ByteString
      getDataTypeBytes() {
    java.lang.Object ref = dataType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dataType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VALUE_FIELD_NUMBER = 7;
  private volatile java.lang.Object value_;
  /**
   * <code>string value = 7;</code>
   */
  public java.lang.String getValue() {
    java.lang.Object ref = value_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      value_ = s;
      return s;
    }
  }
  /**
   * <code>string value = 7;</code>
   */
  public com.google.protobuf.ByteString
      getValueBytes() {
    java.lang.Object ref = value_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      value_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int QUALITY_FIELD_NUMBER = 8;
  private boolean quality_;
  /**
   * <code>bool quality = 8;</code>
   */
  public boolean getQuality() {
    return quality_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getClientHandleBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, clientHandle_);
    }
    if (!getItemNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, itemName_);
    }
    if (active_ != false) {
      output.writeBool(3, active_);
    }
    if (!getAccessPathBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, accessPath_);
    }
    if (timeStamp_ != 0L) {
      output.writeInt64(5, timeStamp_);
    }
    if (!getDataTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, dataType_);
    }
    if (!getValueBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, value_);
    }
    if (quality_ != false) {
      output.writeBool(8, quality_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getClientHandleBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, clientHandle_);
    }
    if (!getItemNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, itemName_);
    }
    if (active_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, active_);
    }
    if (!getAccessPathBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, accessPath_);
    }
    if (timeStamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, timeStamp_);
    }
    if (!getDataTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, dataType_);
    }
    if (!getValueBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, value_);
    }
    if (quality_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(8, quality_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.scm.resources.TagReply)) {
      return super.equals(obj);
    }
    com.scm.resources.TagReply other = (com.scm.resources.TagReply) obj;

    boolean result = true;
    result = result && getClientHandle()
        .equals(other.getClientHandle());
    result = result && getItemName()
        .equals(other.getItemName());
    result = result && (getActive()
        == other.getActive());
    result = result && getAccessPath()
        .equals(other.getAccessPath());
    result = result && (getTimeStamp()
        == other.getTimeStamp());
    result = result && getDataType()
        .equals(other.getDataType());
    result = result && getValue()
        .equals(other.getValue());
    result = result && (getQuality()
        == other.getQuality());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CLIENTHANDLE_FIELD_NUMBER;
    hash = (53 * hash) + getClientHandle().hashCode();
    hash = (37 * hash) + ITEMNAME_FIELD_NUMBER;
    hash = (53 * hash) + getItemName().hashCode();
    hash = (37 * hash) + ACTIVE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getActive());
    hash = (37 * hash) + ACCESSPATH_FIELD_NUMBER;
    hash = (53 * hash) + getAccessPath().hashCode();
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimeStamp());
    hash = (37 * hash) + DATATYPE_FIELD_NUMBER;
    hash = (53 * hash) + getDataType().hashCode();
    hash = (37 * hash) + VALUE_FIELD_NUMBER;
    hash = (53 * hash) + getValue().hashCode();
    hash = (37 * hash) + QUALITY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getQuality());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.scm.resources.TagReply parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.scm.resources.TagReply parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.scm.resources.TagReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.scm.resources.TagReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.scm.resources.TagReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.scm.resources.TagReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.scm.resources.TagReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.scm.resources.TagReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.scm.resources.TagReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.scm.resources.TagReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.scm.resources.TagReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.scm.resources.TagReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.scm.resources.TagReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.scm.resources.TagReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.scm.resources.TagReply)
      com.scm.resources.TagReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.scm.resources.Scmmessages.internal_static_com_scm_resources_TagReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.scm.resources.Scmmessages.internal_static_com_scm_resources_TagReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.scm.resources.TagReply.class, com.scm.resources.TagReply.Builder.class);
    }

    // Construct using com.scm.resources.TagReply.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      clientHandle_ = "";

      itemName_ = "";

      active_ = false;

      accessPath_ = "";

      timeStamp_ = 0L;

      dataType_ = "";

      value_ = "";

      quality_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.scm.resources.Scmmessages.internal_static_com_scm_resources_TagReply_descriptor;
    }

    @java.lang.Override
    public com.scm.resources.TagReply getDefaultInstanceForType() {
      return com.scm.resources.TagReply.getDefaultInstance();
    }

    @java.lang.Override
    public com.scm.resources.TagReply build() {
      com.scm.resources.TagReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.scm.resources.TagReply buildPartial() {
      com.scm.resources.TagReply result = new com.scm.resources.TagReply(this);
      result.clientHandle_ = clientHandle_;
      result.itemName_ = itemName_;
      result.active_ = active_;
      result.accessPath_ = accessPath_;
      result.timeStamp_ = timeStamp_;
      result.dataType_ = dataType_;
      result.value_ = value_;
      result.quality_ = quality_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.scm.resources.TagReply) {
        return mergeFrom((com.scm.resources.TagReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.scm.resources.TagReply other) {
      if (other == com.scm.resources.TagReply.getDefaultInstance()) return this;
      if (!other.getClientHandle().isEmpty()) {
        clientHandle_ = other.clientHandle_;
        onChanged();
      }
      if (!other.getItemName().isEmpty()) {
        itemName_ = other.itemName_;
        onChanged();
      }
      if (other.getActive() != false) {
        setActive(other.getActive());
      }
      if (!other.getAccessPath().isEmpty()) {
        accessPath_ = other.accessPath_;
        onChanged();
      }
      if (other.getTimeStamp() != 0L) {
        setTimeStamp(other.getTimeStamp());
      }
      if (!other.getDataType().isEmpty()) {
        dataType_ = other.dataType_;
        onChanged();
      }
      if (!other.getValue().isEmpty()) {
        value_ = other.value_;
        onChanged();
      }
      if (other.getQuality() != false) {
        setQuality(other.getQuality());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.scm.resources.TagReply parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.scm.resources.TagReply) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object clientHandle_ = "";
    /**
     * <code>string clientHandle = 1;</code>
     */
    public java.lang.String getClientHandle() {
      java.lang.Object ref = clientHandle_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientHandle_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string clientHandle = 1;</code>
     */
    public com.google.protobuf.ByteString
        getClientHandleBytes() {
      java.lang.Object ref = clientHandle_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientHandle_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string clientHandle = 1;</code>
     */
    public Builder setClientHandle(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      clientHandle_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string clientHandle = 1;</code>
     */
    public Builder clearClientHandle() {
      
      clientHandle_ = getDefaultInstance().getClientHandle();
      onChanged();
      return this;
    }
    /**
     * <code>string clientHandle = 1;</code>
     */
    public Builder setClientHandleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      clientHandle_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object itemName_ = "";
    /**
     * <code>string itemName = 2;</code>
     */
    public java.lang.String getItemName() {
      java.lang.Object ref = itemName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        itemName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string itemName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getItemNameBytes() {
      java.lang.Object ref = itemName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        itemName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string itemName = 2;</code>
     */
    public Builder setItemName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      itemName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string itemName = 2;</code>
     */
    public Builder clearItemName() {
      
      itemName_ = getDefaultInstance().getItemName();
      onChanged();
      return this;
    }
    /**
     * <code>string itemName = 2;</code>
     */
    public Builder setItemNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      itemName_ = value;
      onChanged();
      return this;
    }

    private boolean active_ ;
    /**
     * <code>bool active = 3;</code>
     */
    public boolean getActive() {
      return active_;
    }
    /**
     * <code>bool active = 3;</code>
     */
    public Builder setActive(boolean value) {
      
      active_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool active = 3;</code>
     */
    public Builder clearActive() {
      
      active_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object accessPath_ = "";
    /**
     * <code>string accessPath = 4;</code>
     */
    public java.lang.String getAccessPath() {
      java.lang.Object ref = accessPath_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        accessPath_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string accessPath = 4;</code>
     */
    public com.google.protobuf.ByteString
        getAccessPathBytes() {
      java.lang.Object ref = accessPath_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accessPath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string accessPath = 4;</code>
     */
    public Builder setAccessPath(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      accessPath_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string accessPath = 4;</code>
     */
    public Builder clearAccessPath() {
      
      accessPath_ = getDefaultInstance().getAccessPath();
      onChanged();
      return this;
    }
    /**
     * <code>string accessPath = 4;</code>
     */
    public Builder setAccessPathBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      accessPath_ = value;
      onChanged();
      return this;
    }

    private long timeStamp_ ;
    /**
     * <code>int64 timeStamp = 5;</code>
     */
    public long getTimeStamp() {
      return timeStamp_;
    }
    /**
     * <code>int64 timeStamp = 5;</code>
     */
    public Builder setTimeStamp(long value) {
      
      timeStamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 timeStamp = 5;</code>
     */
    public Builder clearTimeStamp() {
      
      timeStamp_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object dataType_ = "";
    /**
     * <code>string dataType = 6;</code>
     */
    public java.lang.String getDataType() {
      java.lang.Object ref = dataType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dataType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string dataType = 6;</code>
     */
    public com.google.protobuf.ByteString
        getDataTypeBytes() {
      java.lang.Object ref = dataType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dataType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string dataType = 6;</code>
     */
    public Builder setDataType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dataType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string dataType = 6;</code>
     */
    public Builder clearDataType() {
      
      dataType_ = getDefaultInstance().getDataType();
      onChanged();
      return this;
    }
    /**
     * <code>string dataType = 6;</code>
     */
    public Builder setDataTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      dataType_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object value_ = "";
    /**
     * <code>string value = 7;</code>
     */
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        value_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string value = 7;</code>
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string value = 7;</code>
     */
    public Builder setValue(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      value_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string value = 7;</code>
     */
    public Builder clearValue() {
      
      value_ = getDefaultInstance().getValue();
      onChanged();
      return this;
    }
    /**
     * <code>string value = 7;</code>
     */
    public Builder setValueBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      value_ = value;
      onChanged();
      return this;
    }

    private boolean quality_ ;
    /**
     * <code>bool quality = 8;</code>
     */
    public boolean getQuality() {
      return quality_;
    }
    /**
     * <code>bool quality = 8;</code>
     */
    public Builder setQuality(boolean value) {
      
      quality_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool quality = 8;</code>
     */
    public Builder clearQuality() {
      
      quality_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.scm.resources.TagReply)
  }

  // @@protoc_insertion_point(class_scope:com.scm.resources.TagReply)
  private static final com.scm.resources.TagReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.scm.resources.TagReply();
  }

  public static com.scm.resources.TagReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TagReply>
      PARSER = new com.google.protobuf.AbstractParser<TagReply>() {
    @java.lang.Override
    public TagReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TagReply(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TagReply> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TagReply> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.scm.resources.TagReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

